import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import './globals.css'
import { AuthProvider } from '../contexts/AuthContext'
import '../styles/editor.css'

 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}